---
title: "UFO Sightings Map"
author: "Sam Gardiner"
date: "27 November 2018"
output:
  html_document:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, error = FALSE)
```

# Packages

```{r packages}
library(leaflet)
library(tidyverse)
library(lubridate)
```

# Import dataset

We're using the [ufo sightings](https://www.kaggle.com/NUFORC/ufo-sightings/version/1) dataset from Kaggle. We import the dataset, set sensible datatypes for each vector, and take a random sample of 2000 sightings to map.

```{r data}
ufo <- read_csv("data/scrubbed.csv",
                col_types = cols(
                  datetime = col_character(),
                  city = col_factor(NULL),
                  state = col_factor(NULL),
                  country = col_factor(NULL),
                  shape = col_factor(NULL),
                  `duration (seconds)` = col_integer(),
                  `duration (hours/min)` = col_character(),
                  comments = col_character(),
                  `date posted` = col_character(),
                  latitude = col_double(),
                  longitude = col_double()
                )) %>%
  mutate_at(vars(datetime, `date posted`), ~parse_date_time(.x, orders = c("mdyHM", "mdy"))) %>%
  mutate(label = str_glue("<em>{datetime}</em>: <br>{comments}"))

ufo_sample <- sample_n(ufo, 2000)
```


# Map

TODO: Map icon shape and colour to sighting properies (especially UFO shape).

```{r}
leaflet(ufo_sample, width = 1000) %>%
  addTiles() %>%
  addMarkers(popup = ~label, clusterOptions = markerClusterOptions())
```


